services:
  # installation composer dependencies
  composer:
    build:
      context: docker/composer
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/html
  # database postgres service
  postgres:
    build:
      context: docker/postgres
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-testing}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-testing}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - 5555:5432
    networks:
      - dockerNetwork
  # symfony service
  symfony:
    build:
      context: .
      dockerfile: docker/symfony/symfony.Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - composer
  # database adminer service
  adminer:
    build:
        context: docker/adminer
        dockerfile: adminer.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - dockerNetwork

networks:
  dockerNetwork:
    driver: bridge